# app.py
# executable dash app

# Import required libraries and modules
import dash
from dash import dcc
from dash import html
import dash_bootstrap_components as dbc
from data_visualization import job_title_wordcloud, skills_wordcloud, create_bar_chart
from data_visualization import create_job_type_cards, make_logo
from callbacks import get_callbacks

# Create a Dash app instance with external_stylesheets
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP], suppress_callback_exceptions=True)
# (Above) indeed-job-title-dropdown, job-title-dropdown, indeed-salary-graph & salary-graph not found
# If you are assigning callbacks to components that are generated by other callbacks 
# (and therefore not in the initial layout), you can suppress this exception by 
# setting suppress_callback_exceptions=True`.

get_callbacks(app)

# Get the base64 encoded wordcloud image
wordcloud_base64 = job_title_wordcloud()

# Define the app layout with various components
app.layout = html.Div([

    # Create job type cards
    create_job_type_cards(),

    # Add a div with a specified height
    html.Div(style={'height': '30px'}),

    # Add tabs for Descriptive Analytics and Predictive Analytics
    dcc.Tabs([
        dcc.Tab(label='Descriptive Analytics', children=[
            html.Div(style={'height': '30px'}),

            # Wordclouds header & divider/spacer
            html.H1("Wordclouds", style={'text-align': 'center', 'margin-top': '50px'}),
            html.Div(style={'height': '20px'}),

            #Specifying the row & columns w/ dash bootstrap components
            #Allows wordcloud images to be displayed next to each other
            dbc.Row([
                dbc.Col([
                    html.H3("Job Title Wordcloud", style={'text-align': 'center', 'margin-top': '50px'}),
                    html.Img(src='data:image/png;base64,{}'.format(job_title_wordcloud()), style={'width': '100%'})
                ], width=6),
                dbc.Col([
                    html.H3("Skills Wordcloud", style={'text-align': 'center', 'margin-top': '50px'}),
                    html.Img(src='data:image/png;base64,{}'.format(skills_wordcloud()), style={'width': '100%'})
                ], width=6)
            ]),

            # Companies with Most Job Listings (w/ Pictures) Header & logo function calls to display pictures
            html.H2("Companies with Most Job Listings", style={'text-align': 'center', 'margin-top': '50px'}),
            html.Div([
                make_logo("Randstad Technologies"),
                make_logo("Motion Recruitment"),
                make_logo("TikTok"),
                make_logo("Comcast")
            ], style={'display': 'flex', 'justify-content': 'center', 'align-items': 'center', 'margin-bottom': '50px'}),

            # 2023 Job Listings Header
            html.H1("2023 Job Listings", style={'text-align': 'center', 'margin-top': '50px'}),
            html.Div(style={'height': '20px'}),

            # Radio buttons to select between Job Listings by Source and by State
            dcc.RadioItems(
                id='job-listings-radio',
                options=[
                    {'label': 'Jobs by State', 'value': 'by_state'},
                    {'label': 'Jobs by Source', 'value': 'by_source'},
                    {'label': 'Top 10 Job States', 'value': 'highest_jobs_by_state'},
                    {'label': 'Bottom 10 Job States', 'value': 'lowest_jobs_by_state'}
                ],
                value='by_state',
                style={
                    'display': 'flex',
                    'flex-direction': 'column',
                    'align-items': 'center'
                }
            ),

            # Container for the Job Listings graph
            html.Div(id='job-listings-container'),

            # Job Titles by State & Salary Header
            html.H1("Job Titles by State & Salary", style={'text-align': 'center', 'margin-top': '50px'}),
            html.Div(style={'height': '20px'}),

            # Radio buttons to select between Simply Hired and Indeed
            dcc.RadioItems(
                id='job-source',
                options=[
                    {'label': 'Simply Hired', 'value': 'simply_hired'},
                    {'label': 'Indeed', 'value': 'indeed'}
                ],
                value='simply_hired',
                style={
                    'display': 'flex',
                    'flex-direction': 'column',
                    'align-items': 'center'
                }
            ),

            # Dropdowns for median salaries per job title header
            html.H1("Median Salaries per Job Title", style={'text-align': 'center', 'margin-top': '50px'}),
            html.Div(id='job-selection-container'),
            # (Above) This container is used to hold and display the content related to job selection, 
            # specifically the dropdown and the graph for job titles by state and salary.
            html.Div([
                dcc.Dropdown(
                    id='type-dropdown',
                    options=[{'label': job_type, 'value': job_type} for job_type in ['Remote', 'Hybrid', 'Onsite']],
                    value='Onsite'
                ),
                dcc.Dropdown(
                    id='title-dropdown',
                    options=[{'label': job_title, 'value': job_title} for job_title in ['Data Engineer', 'Data Analyst', 'Data Scientist', 'Data Architect']],
                    value='Data Engineer'
                ),
                dcc.Dropdown(
                    id='salary_type-dropdown',
                    options=[{'label': salary_type, 'value': salary_type} for salary_type in ['Yearly', 'Hourly']],
                    value='Yearly'
                ),

                # Graph for Median Salaries
                dcc.Graph(id='median-salary-graph')
            ]),

            # Top 5 by Source
            html.H1("Top 5 Job Titles by Source", style={'text-align': 'center', 'margin-top': '50px'}),
            dcc.RadioItems(
                id='top-5-source-radio',
                options=[
                    {'label': 'Indeed', 'value': 'indeed'},
                    {'label': 'Simply Hired', 'value': 'simply_hired'},
                    {'label': 'Dice', 'value': 'dice'}
                ],
                value='indeed',
                style={
                    'display': 'flex',
                    'flex-direction': 'column',
                    'align-items': 'center'
                }
            ),
            html.Div(id='top-5-source-container'),

        ]),


        #Predictive Analytics tab
        dcc.Tab(label='Predictive Analytics', children=[
            
            # Bar chart for jobs by posted_date
            html.H1("Jobs Timeline by Date", style={'text-align': 'center', 'margin-top': '50px'}),
            dcc.Graph(
                id='jobs-by-posted-date',
                figure=create_bar_chart()
            ),

        ]),
    ])
])

# Starts the Dash application server & enables debug mode, which provides additional 
# information and error messages for debugging purposes.
if __name__ == '__main__':
    app.run_server(debug=True)

