# -*- coding: utf-8 -*-
"""SkillsWordCloud.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RSiy1GaTKvt2k-vowz3z8DqfcajVftv5
"""

# Python program to generate WordCloud
 
# importing all necessary modules
import matplotlib.pyplot as plt
import pandas as pd
from wordcloud import WordCloud, STOPWORDS
from PIL import Image
import numpy as np

# Reads 'top_words' file
skills = pd.read_csv(r"C:/Users/battl/Documents/Dash Final Project/Combined CSVs/sorted_skills.csv")
comment_words = ''
stopwords = set(STOPWORDS)
 
# iterate through the csv file
for val in skills.skill:
    
    # typecaste each val to string
    val = str(val)
 
    # split the value
    tokens = val.split()
     
    # Converts each token into lowercase
    for i in range(len(tokens)):
        tokens[i] = tokens[i].lower()

    comment_words += " ".join(tokens)+" "
 
mask = Image.open("C:/Users/battl/Documents/Dash Final Project/Combined CSVs/py_img.png")
mask = mask.resize((800, 800), resample=Image.BILINEAR)
mask = np.array(mask)
wordcloud = WordCloud(width = 500, height = 500,
                background_color ='white',
                stopwords = stopwords,
                min_font_size = 15,
                mask = mask,
                contour_width=3,
                contour_color='#330066').generate(comment_words)
 
# plot the WordCloud image                      
plt.figure(figsize = (6, 6), facecolor = None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad = 0)
 
plt.show()